unit tests, CI update

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -1,16 +1,50 @@
 name: CI
 on: [push]
 
+name: CI
+on: [push]
+
 jobs:
-  black:
+  unittest:
+    name: unit tests
     runs-on: ubuntu-22.04
     steps:
       - uses: actions/checkout@v3
-      - name: Install linters
-        #black is synced with the .pre-commit-hooks version
+
+      - name: Set up Python 
+        uses: actions/setup-python@v4
+        with:
+          python-version: 3.9
+
+      - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
-          pip install black==22.12.0
+          pip install pytest
+          pip install -r tests/requirements.txt
+      - name: Test with pytest
+        run: |
+          python -m pytest
+  lint:
+    runs-on: ubuntu-22.04
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: Install linters
+        # black is synced with the .pre-commit-hooks version
+        run: |
+          python -m pip install --upgrade pip
+          pip install bandit[toml] pycodestyle pylint black==22.12.0
+      - name: Run pycodestyle
+        run: |
+          pycodestyle --max-line-length=120 .
+      - name: Run pylint
+        if: success() || failure() # still run pylint if above checks fail
+        run: |
+          pylint cumulus tests
+      - name: Run bandit
+        if: success() || failure() # still run bandit if above checks fail
+        run: |
+          bandit -c pyproject.toml -r .
       - name: Run black
         if: success() || failure() # still run black if above checks fails
         run: |
